### ISSUE TITLE
Occasional Errno::EBADF via Sidekiq. Thread-safety issues?

### ISSUE THREAD

**Issue by henrik** [customerio/customerio-ruby#101]
Twice now, we've seen `Errno::EBADF: Bad file descriptor` errors from this lib.

It runs in Sidekiq jobs (meaning it's multi-threaded). My suspicion is that it's a thread-safety issue where if two requests overlap, they might both try to close the same connection/socket causing this error.

I'm not close to expert at threading or networking so this is a complete guess.

Backtrace:

```
/opt/ruby/lib/ruby/3.2.0/openssl/ssl.rb:387 :in 'close'
/opt/ruby/lib/ruby/3.2.0/openssl/ssl.rb:387 :in 'sysclose'
/opt/ruby/lib/ruby/3.2.0/openssl/buffering.rb:485 in 'close'
/opt/ruby/lib/ruby/3.2.0/net/http.rb:1357 in 'rescue in connect'
/opt/ruby/lib/ruby/3.2.0/net/http.rb:1253 in 'connect'
/opt/ruby/lib/ruby/3.2.0/net/http.rb:1248 in 'do_start'
/opt/ruby/lib/ruby/3.2.0/net/http.rb:1237 :in 'start'
[GEM_ROOT]/gems/customerio-5.0.0/lib/customerio/base_client.rb:62:in 'execute'
[GEM_ROOT]/gems/customerio-5.0.0/lib/customerio/base_client.rb:28:in 'request'
```

**Comment by hownowstephen** [comment]
Investigated the architecture — `BaseClient#execute` creates a new `Net::HTTP` instance per request and uses the block form of `session.start`, so connections are never shared across threads. Two concurrent Sidekiq jobs using the same `Client` instance each get their own HTTP connection. The `EBADF` was likely a Ruby 3.2.0 OpenSSL binding edge case rather than a client library bug. Closing as not-a-bug — if you're still seeing this on newer Ruby versions, please reopen with details.
